### ISSUE TITLE
Android app crashes after changing icon and trying to get native premission

### ISSUE THREAD

**Issue by ToniLloyds** [true-hamid/rn-dynamic-app-icon#6]
Basically same thing that i reported here https://github.com/skb1129/react-native-change-icon/issues/53
is happening with this package as well.

Can you help me with this ?

Here is a minimal reproducible example with fresh install of react native 
https://github.com/ToniLloyds/example-cahnge-icon-bug

To reproduce 
1. `git clone https://github.com/ToniLloyds/example-cahnge-icon-bug`
2. cd into project directory
3. install dependencies `yarn`
4. Run it `yarn android`
5. After app opens click on "change UK" or "change US"
6. Click Request permission
7. App crashes

**Comment by true-hamid** [comment]
Hi,
App is not crashing but the icon change is triggered while onActivityPaused is called, which happens once a permission intent is triggered.

**Comment by true-hamid** [comment]
One enhancement is to make icon change based on a parameter, so that user have control on when should it be done, @ToniLloyds if you are interested maybe you can take it up

**Comment by true-hamid** [comment]
@ToniLloyds check the new version 0.6.0 I've done the change.
You can now kill the expired activity onActivityPaused or onActivityStopped or onActivityDestroyed based on a parameter you can pass
